"""Reusable maze generation for the 42 *A-Maze-ing* project.

The package exposes a single class, :class:`MazeGenerator`, which builds
either a **perfect** maze (exactly one path between any two cells) or a
**braided** board suitable for a Pac-Man-like game (many loops, no
dead-end).  A "42" pattern made of fully closed cells is drawn in the
middle of the maze whenever it fits.

Install it with ``pip install mazegen-1.0.0-py3-none-any.whl``.

Instantiate and use
-------------------

The maze is generated by the constructor, so a basic example is::

    from mazegen import MazeGenerator

    maze = MazeGenerator(width=20, height=15)
    print(maze)                 # the hexadecimal wall map
    maze.save("maze.txt")       # map + entry + exit + shortest path

Custom parameters
-----------------

Every parameter is optional but ``width`` and ``height``::

    maze = MazeGenerator(
        width=25,               # number of cells, >= 2
        height=19,
        entry=(0, 0),           # (x, y), defaults to the top-left cell
        exit=(24, 18),          # (x, y), defaults to the bottom-right cell
        perfect=True,           # one single path (default: braided board)
        seed=42,                # any int, for a reproducible maze
        pattern=True,           # draw the "42" pattern (default: True)
    )
    maze.generate(seed=7)       # re-roll the same object with a new seed

Access the structure and the solution
-------------------------------------

``maze.grid`` is a list of rows of integers; each integer is a bitmask of
the **closed** walls of one cell: ``NORTH=1``, ``EAST=2``, ``SOUTH=4``,
``WEST=8`` (so ``0`` is a fully open cell and ``15`` a fully closed one).
Helpers avoid touching the bitmask directly::

    maze.grid[y][x]                 # walls of the cell (x, y)
    maze.linked((0, 0), (1, 0))     # can one walk between both cells?
    maze.exits((0, 0))              # number of open sides of a cell
    maze.pattern_cells              # cells used by the "42" pattern
    maze.corridors()                # every cell that is not in the pattern
    maze.dead_ends()                # corridors with a single open side
    maze.loops()                    # number of independent routes

    maze.solve()                    # shortest path, as a list of (x, y)
    maze.path_string()              # the same path, as "SSEENNE..."
    maze.to_hex_rows()              # the wall map, one string per row
"""

from __future__ import annotations

import random
from collections import deque

__all__ = [
    "MazeGenerator",
    "NORTH",
    "EAST",
    "SOUTH",
    "WEST",
    "ALL_WALLS",
    "Cell",
]

Cell = tuple[int, int]

NORTH = 1
EAST = 2
SOUTH = 4
WEST = 8
ALL_WALLS = NORTH | EAST | SOUTH | WEST

#: letter -> (wall bit, dx, dy, wall bit of the neighbour)
DIRECTIONS: dict[str, tuple[int, int, int, int]] = {
    "N": (NORTH, 0, -1, SOUTH),
    "E": (EAST, 1, 0, WEST),
    "S": (SOUTH, 0, 1, NORTH),
    "W": (WEST, -1, 0, EAST),
}

#: The "42" drawing: "1" is a fully closed cell, "0" a normal corridor.
#: Its middle column and middle row are corridors, which keeps the centre
#: of the maze open even when the pattern is centred on it.
PATTERN_42: tuple[str, ...] = (
    "100101111",
    "100100001",
    "100100001",
    "111101111",
    "000101000",
    "000101000",
    "000101111",
)


class MazeGenerator:
    """A maze, generated with a randomised depth-first search.

    Args:
        width: Number of cells per row (>= 2).
        height: Number of cells per column (>= 2).
        entry: Coordinates ``(x, y)`` of the entry cell.
        exit: Coordinates ``(x, y)`` of the exit cell.
        perfect: ``True`` for a single path between entry and exit,
            ``False`` (the default) for a looping, playable board.
        seed: Seed of the random generator, for reproducible mazes.
        pattern: Draw the "42" pattern when the maze is big enough.

    Raises:
        ValueError: If the size is too small, or if entry or exit are
            equal or outside of the maze.
    """

    def __init__(
        self,
        width: int,
        height: int,
        entry: Cell = (0, 0),
        exit: Cell | None = None,
        perfect: bool = False,
        seed: int | None = None,
        pattern: bool = True,
    ) -> None:
        if width < 2 or height < 2:
            raise ValueError("the maze must be at least 2x2 cells")
        if not perfect and width * height <= 4:
            raise ValueError(
                "a playable board needs more than 2x2 cells, as it must "
                "offer at least two independent routes"
            )
        self.width = width
        self.height = height
        self.entry = entry
        self.exit = exit if exit is not None else (width - 1, height - 1)
        self.perfect = perfect
        self.seed = seed
        self.pattern = pattern
        self._inside(self.entry, "ENTRY")
        self._inside(self.exit, "EXIT")
        if self.entry == self.exit:
            raise ValueError("ENTRY and EXIT must be two different cells")
        self.grid: list[list[int]] = []
        self.pattern_cells: set[Cell] = set()
        self.pattern_error: str = ""
        self._rng = random.Random(seed)
        self.generate()

    def _inside(self, cell: Cell, name: str) -> None:
        """Check that `cell` belongs to the maze."""
        size = f"{self.width}x{self.height}"
        if not (0 <= cell[0] < self.width and 0 <= cell[1] < self.height):
            raise ValueError(f"{name} {cell} is outside of the {size} maze")

    # ------------------------------------------------------------------
    # generation
    # ------------------------------------------------------------------

    def generate(self, seed: int | None = None) -> None:
        """Build a brand new maze in place.

        Args:
            seed: New seed to use; the previous one is kept when omitted,
                which makes the very same maze again.
        """
        if seed is not None:
            self.seed = seed
        self._rng = random.Random(self.seed)
        self.grid = [[ALL_WALLS] * self.width for _ in range(self.height)]
        self._place_pattern()
        self._carve()
        if not self.perfect:
            self._braid()

    def _place_pattern(self) -> None:
        """Reserve the cells drawing the "42", in the middle of the maze."""
        self.pattern_cells = set()
        self.pattern_error = ""
        if not self.pattern:
            return
        rows = len(PATTERN_42)
        cols = len(PATTERN_42[0])
        left = self.width // 2 - cols // 2
        top = self.height // 2 - rows // 2
        if (left < 1 or top < 1
                or left + cols > self.width - 1
                or top + rows > self.height - 1):
            self.pattern_error = (
                f'the "42" pattern needs a maze of at least '
                f"{cols + 2}x{rows + 2} cells, it is not drawn"
            )
            return
        cells = {
            (left + x, top + y)
            for y, row in enumerate(PATTERN_42)
            for x, closed in enumerate(row)
            if closed == "1"
        }
        if self.entry in cells or self.exit in cells:
            self.pattern_error = (
                'ENTRY or EXIT stands on the "42" pattern, it is not drawn'
            )
            return
        self.pattern_cells = cells

    def _carve(self) -> None:
        """Dig a spanning tree through every corridor cell (DFS)."""
        stack: list[Cell] = [self.entry]
        visited: set[Cell] = {self.entry}
        while stack:
            cell = stack[-1]
            unseen = [n for _, n in self._neighbours(cell) if n not in visited]
            if not unseen:
                stack.pop()
                continue
            chosen = self._rng.choice(unseen)
            self._open(cell, chosen)
            visited.add(chosen)
            stack.append(chosen)

    def _braid(self) -> None:
        """Remove dead-ends by opening one more wall around each of them.

        Each removed wall adds an independent route to the board, which
        is what a Pac-Man-like game needs.  A wall is kept whenever it
        would create a corridor wider than two cells.
        """
        cells = self.corridors()
        self._rng.shuffle(cells)
        for cell in cells:
            if self.exits(cell) != 1:
                continue
            closed = [n for _, n in self._neighbours(cell)
                      if not self.linked(cell, n)]
            self._rng.shuffle(closed)
            # Merging two dead-ends together fixes both of them at once.
            closed.sort(key=lambda n: self.exits(n) != 1)
            for neighbour in closed:
                self._open(cell, neighbour)
                if self._too_wide(cell, neighbour):
                    self._close(cell, neighbour)
                else:
                    break

    # ------------------------------------------------------------------
    # walls
    # ------------------------------------------------------------------

    @staticmethod
    def _wall_bits(a: Cell, b: Cell) -> tuple[int, int]:
        """Return the wall bit of `a` towards `b`, and the one of `b`."""
        for bit, dx, dy, opposite in DIRECTIONS.values():
            if (a[0] + dx, a[1] + dy) == b:
                return bit, opposite
        raise ValueError(f"{a} and {b} are not neighbours")

    def _open(self, a: Cell, b: Cell) -> None:
        """Remove the wall shared by two neighbouring cells."""
        bit, opposite = self._wall_bits(a, b)
        self.grid[a[1]][a[0]] &= ~bit
        self.grid[b[1]][b[0]] &= ~opposite

    def _close(self, a: Cell, b: Cell) -> None:
        """Put back the wall shared by two neighbouring cells."""
        bit, opposite = self._wall_bits(a, b)
        self.grid[a[1]][a[0]] |= bit
        self.grid[b[1]][b[0]] |= opposite

    def _neighbours(self, cell: Cell) -> list[tuple[str, Cell]]:
        """Every corridor cell touching `cell`, as ``(letter, cell)``."""
        found: list[tuple[str, Cell]] = []
        for letter, (_, dx, dy, _) in DIRECTIONS.items():
            other = (cell[0] + dx, cell[1] + dy)
            if (0 <= other[0] < self.width and 0 <= other[1] < self.height
                    and other not in self.pattern_cells):
                found.append((letter, other))
        return found

    def linked(self, a: Cell, b: Cell) -> bool:
        """Tell whether one can walk straight from `a` to `b`."""
        bit, _ = self._wall_bits(a, b)
        return not self.grid[a[1]][a[0]] & bit

    def exits(self, cell: Cell) -> int:
        """Return the number of open sides of `cell`."""
        return 4 - bin(self.grid[cell[1]][cell[0]]).count("1")

    def _is_open_block(self, left: int, top: int) -> bool:
        """Tell whether the 3x3 block at ``(left, top)`` is fully open."""
        for y in range(top, top + 3):
            for x in range(left, left + 3):
                if x + 1 < left + 3 and not self.linked((x, y), (x + 1, y)):
                    return False
                if y + 1 < top + 3 and not self.linked((x, y), (x, y + 1)):
                    return False
        return True

    def _too_wide(self, a: Cell, b: Cell) -> bool:
        """Tell whether a 3x3 open area appears around the `a`-`b` gap."""
        lefts = range(max(0, min(a[0], b[0]) - 2),
                      min(self.width - 3, max(a[0], b[0])) + 1)
        tops = range(max(0, min(a[1], b[1]) - 2),
                     min(self.height - 3, max(a[1], b[1])) + 1)
        return any(self._is_open_block(x, y) for x in lefts for y in tops)

    # ------------------------------------------------------------------
    # reading the result
    # ------------------------------------------------------------------

    def corridors(self) -> list[Cell]:
        """Return every cell that is not part of the "42" pattern."""
        return [(x, y)
                for y in range(self.height)
                for x in range(self.width)
                if (x, y) not in self.pattern_cells]

    def dead_ends(self) -> list[Cell]:
        """Return the corridors having a single open side."""
        return [cell for cell in self.corridors() if self.exits(cell) == 1]

    def loops(self) -> int:
        """Return the number of independent routes of the maze.

        A perfect maze has none; a playable board needs at least two.
        """
        corridors = self.corridors()
        passages = sum(
            1
            for cell in corridors
            for _, other in self._neighbours(cell)
            if self.linked(cell, other)
        ) // 2
        return passages - len(corridors) + 1

    def solve(self) -> list[Cell]:
        """Return the shortest path from entry to exit, as a list of cells.

        The list is empty when the exit cannot be reached.
        """
        previous: dict[Cell, Cell] = {}
        seen: set[Cell] = {self.entry}
        queue: deque[Cell] = deque([self.entry])
        while queue:
            cell = queue.popleft()
            if cell == self.exit:
                break
            for _, other in self._neighbours(cell):
                if other not in seen and self.linked(cell, other):
                    seen.add(other)
                    previous[other] = cell
                    queue.append(other)
        if self.exit not in seen:
            return []
        path = [self.exit]
        while path[-1] != self.entry:
            path.append(previous[path[-1]])
        path.reverse()
        return path

    def path_string(self) -> str:
        """Return the shortest path as a string of ``N``/``E``/``S``/``W``."""
        moves: list[str] = []
        path = self.solve()
        for a, b in zip(path, path[1:]):
            for letter, (_, dx, dy, _) in DIRECTIONS.items():
                if (a[0] + dx, a[1] + dy) == b:
                    moves.append(letter)
        return "".join(moves)

    def to_hex_rows(self) -> list[str]:
        """Return the maze as one hexadecimal string per row of cells."""
        return ["".join(f"{cell:x}" for cell in row) for row in self.grid]

    def __str__(self) -> str:
        """Return the hexadecimal wall map."""
        return "\n".join(self.to_hex_rows())

    def save(self, filename: str) -> None:
        """Write the maze, its entry, its exit and its solution to a file.

        Args:
            filename: Path of the output file, overwritten if it exists.

        Raises:
            OSError: If the file cannot be written.
        """
        lines = self.to_hex_rows()
        lines += [
            "",
            f"{self.entry[0]},{self.entry[1]}",
            f"{self.exit[0]},{self.exit[1]}",
            self.path_string(),
        ]
        with open(filename, "w", encoding="utf-8") as output:
            output.write("\n".join(lines) + "\n")
